// prisma/seed.ts
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set. Add it to your environment before running seed.");
}

// Prisma v7 requires an explicit driver adapter for all client instantiations.
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding started... 🌱");

  // Clear existing data to avoid duplicates on re-runs
  await prisma.donor.deleteMany();
  console.log("Cleared existing data.");

  await prisma.donor.createMany({
    data: [
      // ---- Pabna District ----
      {
        name: "Abdur Rahman",
        fatherName: "Abdul Karim",
        village: "Shibrampur",
        wardNumber: "3",
        union: "Dapunia",
        postOffice: "Dapunia",
        upazila: "Pabna Sadar",
        district: "Pabna",
        sscYear: "2015",
        sscInstitution: "Pabna Zilla School",
        hscYear: "2017",
        hscInstitution: "Pabna Govt College",
        profession: "Web Developer",
        mobile: "01710000001",
        bloodGroup: "A+",
      },
      {
        name: "Mehedi Hasan",
        fatherName: "Mofiz Uddin",
        village: "Ataikula",
        wardNumber: "5",
        union: "Ataikula",
        postOffice: "Ataikula",
        upazila: "Ishwardi",
        district: "Pabna",
        sscYear: "2016",
        profession: "Teacher",
        mobile: "01710000002",
        bloodGroup: "B+",
      },
      {
        name: "Rakib Hossain",
        fatherName: "Abul Hossain",
        village: "Bera",
        wardNumber: "2",
        upazila: "Bera",
        district: "Pabna",
        sscYear: "2018",
        profession: "Student",
        mobile: "01710000003",
        bloodGroup: "O+",
      },
      {
        name: "Tanvir Ahmed",
        fatherName: "Jalal Uddin",
        village: "Sujanagar",
        wardNumber: "7",
        upazila: "Sujanagar",
        district: "Pabna",
        sscYear: "2014",
        profession: "Bank Officer",
        mobile: "01710000004",
        bloodGroup: "AB+",
      },
      {
        name: "Sabbir Hossain",
        fatherName: "Rafiqul Islam",
        village: "Chatmohar",
        wardNumber: "1",
        upazila: "Chatmohar",
        district: "Pabna",
        sscYear: "2013",
        profession: "Engineer",
        mobile: "01710000005",
        bloodGroup: "A-",
      },
      {
        name: "Naim Islam",
        village: "Santhia",
        wardNumber: "4",
        upazila: "Santhia",
        district: "Pabna",
        sscYear: "2017",
        profession: "Doctor",
        mobile: "01710000006",
        bloodGroup: "B-",
      },
      {
        name: "Imran Khan",
        village: "Faridpur",
        wardNumber: "6",
        upazila: "Faridpur",
        district: "Pabna",
        sscYear: "2012",
        profession: "Police Officer",
        mobile: "01710000007",
        bloodGroup: "O-",
      },
      {
        name: "Faisal Ahmed",
        village: "Bhangura",
        wardNumber: "8",
        upazila: "Bhangura",
        district: "Pabna",
        sscYear: "2011",
        profession: "Businessman",
        mobile: "01710000008",
        bloodGroup: "AB-",
      },

      // ---- Rajshahi District ----
      {
        name: "Saiful Islam",
        village: "Puthia",
        wardNumber: "2",
        upazila: "Puthia",
        district: "Rajshahi",
        sscYear: "2016",
        profession: "Teacher",
        mobile: "01710000009",
        bloodGroup: "A+",
      },
      {
        name: "Jahid Hasan",
        village: "Bagha",
        wardNumber: "3",
        upazila: "Bagha",
        district: "Rajshahi",
        sscYear: "2015",
        profession: "Farmer",
        mobile: "01710000010",
        bloodGroup: "B+",
      },
      {
        name: "Rony Ahmed",
        village: "Godagari",
        wardNumber: "5",
        upazila: "Godagari",
        district: "Rajshahi",
        sscYear: "2014",
        profession: "Driver",
        mobile: "01710000011",
        bloodGroup: "O+",
      },
      {
        name: "Shakib Ali",
        village: "Tanore",
        wardNumber: "1",
        upazila: "Tanore",
        district: "Rajshahi",
        sscYear: "2019",
        profession: "Student",
        mobile: "01710000012",
        bloodGroup: "AB+",
      },

      // ---- Dhaka District ----
      {
        name: "Mahmudul Hasan",
        village: "Dhamrai",
        wardNumber: "9",
        upazila: "Dhamrai",
        district: "Dhaka",
        sscYear: "2013",
        profession: "Software Engineer",
        mobile: "01710000013",
        bloodGroup: "A+",
      },
      {
        name: "Arif Hossain",
        village: "Savar",
        wardNumber: "4",
        upazila: "Savar",
        district: "Dhaka",
        sscYear: "2012",
        profession: "Garments Officer",
        mobile: "01710000014",
        bloodGroup: "B+",
      },
      {
        name: "Nasir Uddin",
        village: "Keraniganj",
        wardNumber: "6",
        upazila: "Keraniganj",
        district: "Dhaka",
        sscYear: "2010",
        profession: "Lawyer",
        mobile: "01710000015",
        bloodGroup: "O+",
      },
      {
        name: "Hasibul Islam",
        village: "Nawabganj",
        wardNumber: "7",
        upazila: "Nawabganj",
        district: "Dhaka",
        sscYear: "2011",
        profession: "Journalist",
        mobile: "01710000016",
        bloodGroup: "AB+",
      },

      // ---- Khulna ----
      {
        name: "Mizanur Rahman",
        village: "Batiaghata",
        wardNumber: "2",
        upazila: "Batiaghata",
        district: "Khulna",
        sscYear: "2009",
        profession: "Engineer",
        mobile: "01710000017",
        bloodGroup: "A-",
      },
      {
        name: "Kamal Hossain",
        village: "Dacope",
        wardNumber: "3",
        upazila: "Dacope",
        district: "Khulna",
        sscYear: "2008",
        profession: "Businessman",
        mobile: "01710000018",
        bloodGroup: "B-",
      },

      // ---- Chattogram ----
      {
        name: "Ashraful Islam",
        village: "Rangunia",
        wardNumber: "5",
        upazila: "Rangunia",
        district: "Chattogram",
        sscYear: "2014",
        profession: "Teacher",
        mobile: "01710000019",
        bloodGroup: "O-",
      },
      {
        name: "Belal Hossain",
        village: "Sitakunda",
        wardNumber: "1",
        upazila: "Sitakunda",
        district: "Chattogram",
        sscYear: "2013",
        profession: "Marine Engineer",
        mobile: "01710000020",
        bloodGroup: "AB-",
      },

      // ---- Various Districts ----
      {
        name: "Minhaz Uddin",
        village: "Gaibandha Sadar",
        wardNumber: "4",
        upazila: "Gaibandha Sadar",
        district: "Gaibandha",
        sscYear: "2020",
        profession: "Student",
        mobile: "01710000021",
        bloodGroup: "A+",
      },
      {
        name: "Habibur Rahman",
        village: "Bogura Sadar",
        wardNumber: "6",
        upazila: "Bogura Sadar",
        district: "Bogura",
        sscYear: "2007",
        profession: "Farmer",
        mobile: "01710000022",
        bloodGroup: "B+",
      },
      {
        name: "Shariful Islam",
        village: "Natore Sadar",
        wardNumber: "3",
        upazila: "Natore Sadar",
        district: "Natore",
        sscYear: "2015",
        profession: "Doctor",
        mobile: "01710000023",
        bloodGroup: "O+",
      },
      {
        name: "Al Amin",
        village: "Sirajganj Sadar",
        wardNumber: "8",
        upazila: "Sirajganj Sadar",
        district: "Sirajganj",
        sscYear: "2016",
        profession: "Teacher",
        mobile: "01710000024",
        bloodGroup: "AB+",
      },
      {
        name: "Shahin Alam",
        village: "Kushtia Sadar",
        wardNumber: "2",
        upazila: "Kushtia Sadar",
        district: "Kushtia",
        sscYear: "2011",
        profession: "Banker",
        mobile: "01710000025",
        bloodGroup: "A-",
      },
      {
        name: "Rashedul Islam",
        village: "Jessore Sadar",
        wardNumber: "5",
        upazila: "Jessore Sadar",
        district: "Jashore",
        sscYear: "2012",
        profession: "Engineer",
        mobile: "01710000026",
        bloodGroup: "B-",
      },
      {
        name: "Sumon Ahmed",
        village: "Barishal Sadar",
        wardNumber: "7",
        upazila: "Barishal Sadar",
        district: "Barishal",
        sscYear: "2013",
        profession: "Businessman",
        mobile: "01710000027",
        bloodGroup: "O-",
      },
      {
        name: "Zahidul Islam",
        village: "Cumilla Sadar",
        wardNumber: "4",
        upazila: "Cumilla Sadar",
        district: "Cumilla",
        sscYear: "2018",
        profession: "Student",
        mobile: "01710000028",
        bloodGroup: "AB-",
      },
      {
        name: "Mamun Hossain",
        village: "Feni Sadar",
        wardNumber: "1",
        upazila: "Feni Sadar",
        district: "Feni",
        sscYear: "2014",
        profession: "Teacher",
        mobile: "01710000029",
        bloodGroup: "A+",
      },
      {
        name: "Tariq Hasan",
        village: "Noakhali Sadar",
        wardNumber: "6",
        upazila: "Noakhali Sadar",
        district: "Noakhali",
        sscYear: "2015",
        profession: "Doctor",
        mobile: "01710000030",
        bloodGroup: "B+",
      },
    ],
  });

  console.log("✅ 30 real-world sample donors seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

